---
abstract: "Perl module to interact with Google's ClientLogin protocol"
author:
  - 'Alessandro Ghedini <alexbio@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Google-Auth-ClientLogin
requires:
  Carp: 0
  HTTP::Tiny: 0
resources:
  bugtracker: https://github.com/AlexBio/WWW-Google-Auth-ClientLogin/issues
  homepage: http://search.cpan.org/dist/WWW-Google-Auth-ClientLogin/
  repository: git://github.com/AlexBio/WWW-Google-Auth-ClientLogin.git
version: 0.04
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::ALEXBIO/@Basic/GatherDir'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::ALEXBIO/@Basic/PruneCruft'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::ALEXBIO/@Basic/ManifestSkip'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::ALEXBIO/@Basic/MetaYAML'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::ALEXBIO/@Basic/License'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::ALEXBIO/@Basic/Readme'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::ALEXBIO/@Basic/ExtraTests'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::ALEXBIO/@Basic/ExecDir'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::ALEXBIO/@Basic/ShareDir'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::ALEXBIO/@Basic/MakeMaker'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::ALEXBIO/@Basic/Manifest'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::ALEXBIO/@Basic/TestRelease'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::ALEXBIO/@Basic/ConfirmRelease'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::ALEXBIO/@Basic/UploadToCPAN'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@Author::ALEXBIO/@GitHub/GitHub::Meta'
      version: 0.08
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@Author::ALEXBIO/@GitHub/GitHub::Update'
      version: 0.08
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::ALEXBIO/MetaConfig'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::ALEXBIO/MetaJSON'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::ALEXBIO/AutoPrereqs'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::PodVersion
      name: '@Author::ALEXBIO/PodVersion'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::ALEXBIO/PkgVersion'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ChangelogFromGit
      name: '@Author::ALEXBIO/ChangelogFromGit'
      version: 0.002
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::ALEXBIO/Git::Tag'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::ALEXBIO/Git::Push'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::ALEXBIO/InstallRelease'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::Clean
      name: '@Author::ALEXBIO/Clean'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.200006
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200006
